version: "3.8"
services:
  db-dev:
    image: postgres:latest
    ports:
      - "5432:5432" # porta_servidor:porta_docker
    container_name: "db-dev"
    restart: always # reinicia o DB apos o servidor reiniciar
    volumes:
      - ./db-dev-backup:/var/lib/postgresql/data # cria backup do DB no servidor
    environment:
      POSTGRES_USER: pguser # Usuario do db: mudar no .env
      POSTGRES_PASSWORD: pgpassword
volumes:
  db-dev-backup: # nome da pasta que vai conter o backup do DB no servidor